title: PROGRAMMING REVIEW
logo: /assets/img/logo.png
description: Catching the latest programming trends.
url: https://programming-review.com
lang: en
theme: minima
footer: © <a href="https://programming-review.com">PROGRAMMING REVIEW 2010-2025</a>
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
build_revision: 21
excerpt_separator: [[[]]]
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
